baseURL = "http://behaiku.org/"
languageCode = "zh-cn"
title = "码农农场"
hasCJKLanguage=true #统计汉字
theme = "mainroad" #主题
paginate = 16 #每页文章数

enableEmoji = true 
enableRobotsTXT = true # robots.txt
preserveTaxonomyNames = true
disablePathToLower = true # 禁止将路径全部改为小写

disqusShortname = "imkerberos"
googleAnalytics = "UA-30583028-1"

[Author]
name = "Eviler"
avatar = "img/avatar.png"

[Params]
subtitle = "种下去的是代码，收获的是 Bug。"
description = "关于一切的 Blog"
copyright = "Eviler"
opengraph = true
twitter_cards = true
readmore = false
authorbox = true
toc = false
post_navigation = true
post_meta = ["date", "categories", "translations"]
#mainSections = ["Home", "Blog", "About"]
dateformat = "2006-01-02"
mathjax = true
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
highlightColor = "#e22d30" 
#customCSS = ["css/custom.css"] # Include custom CSS files
#customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
home = "right"
list = "left"
single = false
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
recent_num = 8
tags_counter = false

[Params.widgets.social]
github = "imkerberos"
facebook = "kerberos.zhang"

[[menu.main]]
identifier = "Home"
weight = -100

[[menu.main]]
identifier = "Blog"
weight = -50

[[menu.main]]
identifier = "About"
weight = 0
