baseURL = "http://behaiku.org/"
languageCode = "zh-cn"
title = "码农农场"
hasCJKLanguage=true #统计汉字
theme = "mainroad" #主题
paginate = 16 #每页文章数

enableEmoji = true 
enableRobotsTXT = true # robots.txt
preserveTaxonomyNames = true
disablePathToLower = true # 禁止将路径全部改为小写

[Author]
name = "Eviler"
avatar = "img/avatar.png"

[Params]
subtitle = "种下去的时代码，收获的是 Bug。"

[Params.sidebar]
home = "right"
list = "left"
single = false
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
recent_num = 8
tags_counter = false

[Params.widgets.social]
github = "imkerberos"
